# Generated by Django 5.0.2 on 2024-07-13 08:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_title', models.CharField(default='', max_length=100)),
                ('item_content', models.CharField(blank=True, max_length=1000, null=True)),
                ('item_type', models.CharField(default='', help_text='这是用来记录元素的主类型，例如文章或标签', max_length=5)),
                ('item_subtype', models.CharField(blank=True, help_text='这是用来记录元素的细分类型，例如文章下的国家法律或公社契约等', max_length=5, null=True)),
                ('item_status', models.CharField(default='', max_length=5)),
                ('time_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_effective', models.DateTimeField(blank=True, null=True)),
                ('user0id', models.IntegerField(blank=True, null=True)),
                ('user0name', models.CharField(default='', max_length=100)),
                ('user1id', models.IntegerField(blank=True, null=True)),
                ('user1name', models.CharField(default='', max_length=100)),
                ('itemXid', models.IntegerField(blank=True, null=True)),
                ('attachment', models.IntegerField(blank=True, null=True)),
                ('sparefield0', models.CharField(default='', help_text='这是备用字段，用来存储用户的密码', max_length=999)),
                ('sparefield1', models.CharField(default='', max_length=99)),
                ('sparefield2', models.CharField(default='', max_length=99)),
                ('sparefield3', models.CharField(default='', max_length=99)),
            ],
            options={
                'verbose_name': '各种元素的详细信息',
                'verbose_name_plural': '各种元素的详细信息',
                'db_table': 'iteminfo',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('op_id', models.AutoField(primary_key=True, serialize=False)),
                ('op_type', models.CharField(default='', max_length=5)),
                ('op_status', models.CharField(blank=True, max_length=5, null=True)),
                ('op_range', models.IntegerField(blank=True, null=True)),
                ('op_time', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=99, null=True)),
                ('ps_content', models.CharField(blank=True, max_length=999, null=True)),
                ('ps_type', models.CharField(blank=True, max_length=5, null=True)),
                ('ps_attitude', models.CharField(blank=True, max_length=5, null=True)),
                ('ps_encrypted', models.IntegerField(blank=True, null=True)),
                ('item0id', models.IntegerField(blank=True, null=True)),
                ('item0title', models.CharField(blank=True, max_length=99, null=True)),
                ('item0type', models.CharField(blank=True, max_length=5, null=True)),
                ('item1id', models.IntegerField(blank=True, null=True)),
                ('item1title', models.CharField(blank=True, max_length=99, null=True)),
                ('item1type', models.CharField(blank=True, max_length=5, null=True)),
                ('userXid', models.IntegerField(blank=True, null=True)),
                ('userXname', models.CharField(blank=True, max_length=99, null=True)),
                ('sparefield0', models.CharField(blank=True, max_length=99, null=True)),
                ('sparefield1', models.CharField(blank=True, max_length=99, null=True)),
                ('sparefield2', models.CharField(blank=True, max_length=99, null=True)),
                ('sparefield3', models.CharField(blank=True, max_length=99, null=True)),
            ],
            options={
                'verbose_name': '操作信息',
                'verbose_name_plural': '操作信息',
                'db_table': 'operation',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('item_id', models.IntegerField(help_text='相关元素的id号，不能自增，被动写入', primary_key=True, serialize=False)),
                ('followed0', models.IntegerField(blank=True, help_text='关注-全量', null=True)),
                ('followed1', models.IntegerField(blank=True, help_text='关注-特别关注', null=True)),
                ('followed2', models.IntegerField(blank=True, help_text='关注-悄悄关注-仅对用户', null=True)),
                ('like', models.IntegerField(blank=True, help_text='赞', null=True)),
                ('unlike', models.IntegerField(blank=True, help_text='踩', null=True)),
                ('share0', models.IntegerField(blank=True, help_text='分享-全量', null=True)),
                ('share1', models.IntegerField(blank=True, help_text='分享-强烈推荐', null=True)),
                ('replied0', models.IntegerField(blank=True, help_text='评论或回复-全量', null=True)),
                ('replied1', models.IntegerField(blank=True, help_text='评论或回复-点赞支持', null=True)),
                ('replied2', models.IntegerField(blank=True, help_text='评论或回复-吐槽异议', null=True)),
                ('replied3', models.IntegerField(blank=True, help_text='评论或回复-质疑困惑', null=True)),
                ('contain', models.IntegerField(blank=True, help_text='包含内容的数量', null=True)),
                ('link0', models.IntegerField(blank=True, help_text='关联-全量', null=True)),
                ('link1', models.IntegerField(blank=True, help_text='关联-互补互证', null=True)),
                ('link2', models.IntegerField(blank=True, help_text='关联-互相矛盾', null=True)),
                ('time_update', models.DateTimeField(blank=True, help_text='更新时间', null=True)),
                ('searched', models.IntegerField(blank=True, help_text='某元素搜索后选中查看的数量', null=True)),
                ('searched_word', models.CharField(blank=True, help_text='仅用户可见，用户搜索的', max_length=99, null=True)),
                ('sparefield0', models.CharField(blank=True, max_length=99, null=True)),
                ('sparefield1', models.CharField(blank=True, max_length=99, null=True)),
                ('sparefield2', models.CharField(blank=True, max_length=99, null=True)),
                ('sparefield3', models.CharField(blank=True, max_length=99, null=True)),
            ],
            options={
                'verbose_name': '各种元素的统计表',
                'verbose_name_plural': '各种元素的统计表',
                'db_table': 'statistic',
            },
        ),
    ]
