# Generated by Django 5.0.2 on 2024-07-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aworld20240617', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminfo',
            name='itemXsn',
            field=models.IntegerField(blank=True, help_text='这仅对于段落和数集类型，用来表示他在文集中的顺序', null=True),
        ),
    ]
